name: build

on:
  workflow_dispatch
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install java
        run: sudo apt install -y default-jre
      - name: build
        run: ./gradlew buildPlugin && cd build/distributions && ls -la && pwd
      - name: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/intellij-qml/intellij-qml/build/distributions/*.zip
          asset_name: blackjack-linux
          tag: ${{ github.ref }}
          overwrite: true
          body: "First release"
