name: build

on:
  workflow_dispatch
      
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: install java
        run: sudo apt install -y default-jre
      - name: build
        run: ./gradlew buildPlugin
  
