name: build

on:
  workflow_dispatch
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install java
        run: sudo apt install -y default-jre
      - name: build
        run: ./gradlew buildPlugin
      - name: release
        uses: actions/upload-artifact@v2.2.3
        with:
          path: build/distributions
