name: build

on:
  push:
    tags:
      - v*
      
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: install java
        run: sudo apt install -y default-jre
      - name: build
        run: ./gradlew buildPlugin
  
